### PR TITLE
allow decoding PBNode fields in any order

### PR DESCRIPTION
**Pull request by mvdan**
(see commit message)

### CODE REVIEW

**Review by willscott — APPROVED** [review]

**Review by hannahhoward — COMMENTED** [review]
There is still one hidden requirement here, which is that Links, which is a repeated field, is not interspersed with Data, which is technically something permitted in the general protobuf spec, though hopefully still prohibited by the revised DagPB spec.

If that is not the case (interspersion is permitted), we should make the parser handle that.

**Comment by mvdan** [comment]
You're right that that's an edge case that's not clearly laid out here. The new spec does imply that it must not be permitted when decoding:

> Duplicate entries in the binary form are invalid; blocks with duplicate field values should be rejected. (Note that it is common for Protobuf decoders to accept repeated field values in the binary data, and interpret them as _updates_ to fields that have already been set; DAG-PB is stricter than this.)

I'm fairly sure that this new code forbids Links-Data-Links, too, but I'll add a test to make sure.

**Comment by mvdan** [comment]
> I'll add a test to make sure.

That test is now added.

**Comment by mvdan** [comment]
I confirmed that the t0110-gateway sharness test succeeds on go-ipfs now.

**Review by willscott — APPROVED** [review]

**Pull request merged**
