### PR TITLE
use go-ipld-prime scratch.Reader

### PR DESCRIPTION
**Pull request by rvagg**
for @warpfork

This doesn't work. Maybe to do with the complex logic required for `Readn1()` and `Unreadn1()`?

All tests fail with this change, not all with the same reason either. Some are `unexpected EOF` and some seem to be seeing the same data repeated (`duplicate Name section`).

### CODE REVIEW

**Comment by mvdan** [comment]
Did this fly under our radar? Just found it by searching for forgotten Go PRs :)

**Comment by rvagg** [comment]
I've put it aside for revisiting, I can't make the new reader work, I'd like to so I can get rid of the refmt dependency, but it seems there's either API differences or a bug and the time investment just now isn't worth it, for me at least. You're welcome to look into it though! I'm sure you could power through solving this one with your Go eyes.

**Comment by mvdan** [comment]
https://github.com/ipld/go-codec-dagpb/pull/21 is my take on this; it parses a `[]byte` instead. See the PR for more details.

I'm not saying "no" to something like scratch.Reader forever, and I'm happy for someone else to take a stab at it in the future while benchmarking. But I do think that there's an inherent overhead in such reader wrappers that we can't afford if we want to make this codec usable in dagpb without a significant slow-down.

**Comment by rvagg** [comment]
:thumbsup: if we're optimizing for smaller block sizes then scrapping streaming parsing is the way to go and fine by me

**Comment by mvdan** [comment]
> usable in dagpb

I meant usable in go-merkledag, of course :) Its block sizes do tend to be small, and it uses buffers anyway.

**Pull request closed without merging**
