### PR TITLE
Revert "chore(mod): update dependencies" + v1.3.2

### PR DESCRIPTION
**Pull request by rvagg**
for those that want this module without the dependencies upgraded - revert the dep upgrade and bump to 1.3.2 (I assume doing both in the same PR is OK)

will post a PR after this with a 1.3.3 with the deps upgraded

### CODE REVIEW

**Comment by rvagg** [comment]
@mvdan can you help me with the go.sum, running `go mod tidy` just wants to bump ipld-prime again to 0.16, I can't get it to stick to 0.11 no matter what I try

**Comment by mvdan** [comment]
Looking.

**Comment by mvdan** [comment]
Ah, it's sorta my fault. The added fuzz func uses the node/basicnode package, which was added sometime between v0.11 and v0.16, so `go mod tidy` tries to upgrade ipld-prime to find the package - and it succeeds at that.

```
$ go mod tidy
go: finding module for package github.com/ipld/go-ipld-prime/node/basicnode
go: found github.com/ipld/go-ipld-prime/node/basicnode in github.com/ipld/go-ipld-prime v0.16.0
```

So the fix is to release v1.3.2 without the fuzz commit, either. I'll push that revert.

**Comment by mvdan** [comment]
Actually, at this point we're reverting pretty much everything, so I think it would be easiest to release v1.3.2 as a cherry-pick of the proto change on top of v1.3.0 on a branch. I'll try to do that.

**Comment by mvdan** [comment]
We did https://github.com/ipld/go-codec-dagpb/pull/40 instead :)

**Pull request closed without merging**
